import type { Job, Company, StatsResponse, Event } from '@jobhunt/contracts';
import type { RecruiterContact, InboundMessage, OutreachPreset, ProxyHealthItem, PlatformAuthInfo } from '../types';

export const INITIAL_PLATFORMS: PlatformAuthInfo[] = [
  {
    id: 'linkedin',
    name: 'LinkedIn',
    category: 'social_portal',
    icon: 'fa-brands fa-linkedin',
    iconColor: 'text-[#0A66C2]',
    status: 'disconnected',
    authMethod: 'extension_bridge',
    dailyQuotaUsed: 0,
    dailyQuotaMax: 12,
    description: 'Residential MV3 Extension session bridge for 1-click EasyApply & Recruiter InMail messaging.',
  },
  {
    id: 'naukri',
    name: 'Naukri.com',
    category: 'job_board',
    icon: 'fa-solid fa-briefcase',
    iconColor: 'text-[#00B4D8]',
    status: 'disconnected',
    authMethod: 'session_cookie',
    dailyQuotaUsed: 0,
    dailyQuotaMax: 30,
    description: 'Direct apply dispatcher & daily automated profile-freshness touch to boost recruiter search ranking.',
  },
  {
    id: 'gmail',
    name: 'Gmail & Google Cloud',
    category: 'communication',
    icon: 'fa-solid fa-envelope',
    iconColor: 'text-[#EA4335]',
    status: 'connected',
    authMethod: 'oauth2',
    accountIdentifier: 'aravindhan.dev@gmail.com',
    lastSyncedAt: 'Real-time Pub/Sub Webhook Active',
    dailyQuotaUsed: 5,
    dailyQuotaMax: 50,
    description: 'Inbound interview sentiment classification & real-time Workday verification OTP push injection.',
    credentials: { webhookUrl: 'http://localhost:4000/webhooks/gmail/push' },
  },
  {
    id: 'cutshort',
    name: 'Cutshort & Instahyre',
    category: 'job_board',
    icon: 'fa-solid fa-paper-plane',
    iconColor: 'text-accent-emerald',
    status: 'disconnected',
    authMethod: 'session_cookie',
    dailyQuotaUsed: 0,
    dailyQuotaMax: 20,
    description: 'Direct hiring manager & founders outreach for verified tech startups.',
  },
  {
    id: 'greenhouse',
    name: 'Greenhouse Public Board API',
    category: 'ats',
    icon: 'fa-solid fa-layer-group',
    iconColor: 'text-amber-400',
    status: 'connected',
    authMethod: 'public_board',
    accountIdentifier: 'Stripe, Postman, Grafana Labs (Synced)',
    lastSyncedAt: '12 mins ago',
    dailyQuotaUsed: 5,
    dailyQuotaMax: 50,
    description: 'Zero-auth public careers board JSON scraper & form payload generator.',
  },
  {
    id: 'lever',
    name: 'Lever & Ashby Public APIs',
    category: 'ats',
    icon: 'fa-solid fa-bolt',
    iconColor: 'text-cyan-400',
    status: 'connected',
    authMethod: 'public_board',
    accountIdentifier: 'OpenAI, Palantir, Vercel (Synced)',
    lastSyncedAt: '12 mins ago',
    dailyQuotaUsed: 3,
    dailyQuotaMax: 50,
    description: 'Zero-auth public careers board JSON scraper for high-growth tech companies.',
  },
  {
    id: 'gemini',
    name: 'Google Gemini 2.0 Flash',
    category: 'ai_service',
    icon: 'fa-solid fa-brain',
    iconColor: 'text-purple-400',
    status: 'connected',
    authMethod: 'api_key',
    accountIdentifier: 'Gemini 2.0 Flash (Cached Context -90% Cost)',
    lastSyncedAt: 'Active',
    description: 'Truth-constrained ATS resume tailoring, cover letter generation, and smart email drafting.',
    credentials: { apiKey: 'AIzaSy...' },
  },
  {
    id: 'apify',
    name: 'Apify Actor Hub',
    category: 'ai_service',
    icon: 'fa-solid fa-spider',
    iconColor: 'text-emerald-400',
    status: 'disconnected',
    authMethod: 'api_key',
    dailyQuotaUsed: 0,
    dailyQuotaMax: 100,
    description: 'Cloud scraper actors for deep LinkedIn & Naukri search without residential proxy fatigue.',
  },
  {
    id: 'hunter',
    name: 'Hunter.io & Clearbit',
    category: 'ai_service',
    icon: 'fa-solid fa-crosshairs',
    iconColor: 'text-orange-400',
    status: 'disconnected',
    authMethod: 'api_key',
    dailyQuotaUsed: 0,
    dailyQuotaMax: 25,
    description: 'Verified engineering manager & recruiter email enrichment engine.',
  },
];

export const INITIAL_PROXY_HEALTH: ProxyHealthItem[] = [
  {
    portal: 'LinkedIn EasyApply',
    icon: 'fa-brands fa-linkedin',
    color: 'text-blue-400',
    integration: 'Manifest V3 Extension (Residential IP)',
    dailyCap: 12,
    usedToday: 4,
    delayModel: 'Gaussian μ=4.5s (σ=1.2s)',
    status: 'Optimal',
    flags: 0,
  },
  {
    portal: 'Naukri.com',
    icon: 'fa-solid fa-briefcase',
    color: 'text-emerald-400',
    integration: 'Local Extension Bridge + Profile Touch',
    dailyCap: 30,
    usedToday: 11,
    delayModel: 'Gaussian μ=3.2s (σ=0.9s)',
    status: 'Optimal',
    flags: 0,
  },
  {
    portal: 'Workday Direct',
    icon: 'fa-solid fa-building',
    color: 'text-purple-400',
    integration: 'Assisted Run + Pub/Sub OTP Webhook',
    dailyCap: 15,
    usedToday: 2,
    delayModel: 'OTP Async Pub/Sub + Human Gate',
    status: 'Active',
    flags: 0,
  },
  {
    portal: 'Greenhouse ATS',
    icon: 'fa-solid fa-layer-group',
    color: 'text-amber-400',
    integration: 'Direct Public JSON + Extension Fill',
    dailyCap: 15,
    usedToday: 5,
    delayModel: 'Direct Public Board API',
    status: 'Optimal',
    flags: 0,
  },
  {
    portal: 'Lever / Ashby ATS',
    icon: 'fa-solid fa-bolt',
    color: 'text-cyan-400',
    integration: 'Direct Public Board API',
    dailyCap: 15,
    usedToday: 3,
    delayModel: 'Direct Public Board API',
    status: 'Optimal',
    flags: 0,
  },
];

export const INITIAL_RECRUITERS: RecruiterContact[] = [
  {
    id: 'rec-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@stripe.com',
    company: 'Stripe',
    role: 'Lead Tech Recruiter',
    channels: ['gmail', 'linkedin'],
    status: 'Outreach Drafted',
    stage: 1,
    lastContacted: '2 hours ago',
    notes: 'Recruiting for Core Payments Infrastructure (Senior Full Stack).',
  },
  {
    id: 'rec-2',
    name: 'Priya Sharma',
    email: 'priya.sharma@postman.com',
    company: 'Postman',
    role: 'Senior Engineering Talent Partner',
    channels: ['linkedin', 'cutshort'],
    status: 'InMail Sent',
    stage: 2,
    lastContacted: '1 day ago',
    notes: 'Requested profile details for API Platform team.',
  },
  {
    id: 'rec-3',
    name: 'Alex Rivera',
    email: 'alex.rivera@openai.com',
    company: 'OpenAI',
    role: 'Technical Sourcing Lead',
    channels: ['gmail'],
    status: 'Interview Scheduled',
    stage: 3,
    lastContacted: 'Yesterday',
    notes: 'Technical screen confirmed for Thursday 4:00 PM IST.',
  },
];

export const INITIAL_INBOX: InboundMessage[] = [
  {
    id: 'msg-1',
    sender: 'Alex Rivera',
    senderEmail: 'alex.rivera@openai.com',
    company: 'OpenAI',
    channel: 'Gmail',
    subject: 'OpenAI Technical Screen Invitation — Senior Full Stack Lead',
    preview: 'Hi Aravindhan, we were impressed by your background in distributed systems and...',
    body: `Hi Aravindhan,

Thank you for your application to OpenAI. We reviewed your profile and were impressed by your background in distributed systems, TypeScript architecture, and developer platforms.

We would love to invite you to a 45-minute technical conversation with one of our Engineering Leads. Please select a time that works for you from the scheduling link below:

https://calendly.com/openai-engineering/aravindhan-screen

Best regards,
Alex Rivera
Technical Sourcing Lead | OpenAI`,
    sentiment: 'Interview Request',
    receivedAt: '10:45 AM Today',
    replyDraft: `Hi Alex,

Thank you for the update! I am excited about the opportunity to discuss the Senior Full Stack role with OpenAI. I have booked Thursday at 4:00 PM IST on your Calendly.

Looking forward to our conversation!

Best regards,
Aravindhan Sivaraman`,
    read: false,
  },
  {
    id: 'msg-2',
    sender: 'Priya Sharma',
    senderEmail: 'priya.sharma@postman.com',
    company: 'Postman',
    channel: 'LinkedIn',
    subject: 'Senior Full Stack Lead opening at Postman Bangalore / Remote',
    preview: 'Hi Aravindhan, I came across your GitHub and noticed your work on high-throughput Fastify APIs...',
    body: `Hi Aravindhan,

I came across your GitHub and noticed your work on high-throughput Fastify and React architectures. We have an open Senior Full Stack Lead role on our Core API Workspace team that aligns directly with your experience.

Would you be open to a brief chat this week?

Best,
Priya Sharma
Senior Talent Partner, Postman`,
    sentiment: 'Inquiry',
    receivedAt: 'Yesterday 4:15 PM',
    replyDraft: `Hi Priya,

Thank you for reaching out! Postman's developer ecosystem is fantastic, and my background in scaling Node.js/TypeScript microservices and modern frontends is a strong match.

I would be happy to connect this week. Please feel free to share a brief agenda or calendar invite.

Best regards,
Aravindhan`,
    read: true,
  },
  {
    id: 'msg-3',
    sender: 'Stripe Careers Team',
    senderEmail: 'notifications@stripe.com',
    company: 'Stripe',
    channel: 'Gmail',
    subject: 'Stripe Coding Assessment Invitation — Senior Full Stack',
    preview: 'Please complete your technical assessment on HackerRank within 5 days...',
    body: `Dear Aravindhan,

Your application for the Senior Full Stack Engineer (Remote - India) position has passed initial screening.

The next step is a 90-minute hands-on coding assessment focusing on React components and API integration.

Link: https://app.hackerrank.com/tests/stripe-fullstack-8921

Please complete this by Sunday midnight.`,
    sentiment: 'Technical Assessment',
    receivedAt: 'Aug 24, 6:30 PM',
    replyDraft: `Thank you for the assessment invitation. I have received the HackerRank link and plan to complete it on Saturday afternoon.`,
    read: true,
  },
];

export const OUTREACH_PRESETS: Record<string, OutreachPreset> = {
  linkedin: {
    id: 'preset-inmail-fast',
    name: 'LinkedIn InMail — Direct Technical Fit',
    channel: 'linkedin',
    constraint: 'Under 300 characters, no fluff, direct match',
    bodyTemplate: `Hi {first_name}, I noticed your opening for {role} at {company}. With 5.5+ YOE leading React 19 & high-throughput Node.js microservices on GCP, my background directly aligns with your stack. Would love 5 mins to chat.`,
  },
  gmail: {
    id: 'preset-email-cold',
    name: 'Cold Recruiter Pitch — High Conversion',
    channel: 'gmail',
    constraint: 'Under 150 words, highlights production metrics',
    subjectTemplate: `{role} Application — Aravindhan Sivaraman (5.5+ YOE Full Stack Lead)`,
    bodyTemplate: `Hi {first_name},

I recently submitted my application for the {role} role at {company}.

Given your team's focus on scalable systems, here is a quick snapshot of my production background:
• 5.5+ YOE architecting React 19/TypeScript frontends and sub-50ms Fastify microservices.
• Scaled background workers handling 50k+ daily payloads on GCP Cloud Run.
• Test-driven approach with 90%+ test coverage.

I have attached my tailored resume and would welcome the chance to discuss how I can contribute to {company}'s roadmap.

Best regards,
Aravindhan Sivaraman
Tambaram, Chennai | GitHub: github.com/aravindhan`,
  },
  cutshort: {
    id: 'preset-cutshort-ping',
    name: 'Cutshort / Instahyre Founder Ping',
    channel: 'cutshort',
    constraint: 'Fast, informal, engineering-focused',
    bodyTemplate: `Hey {first_name}, excited about what {company} is building. I am a Senior Full Stack Lead (5.5+ YOE) specializing in React, TypeScript & distributed Node.js backends. Open to discussing leadership opportunities.`,
  },
};

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-stripe',
    name: 'Stripe',
    normalizedName: 'stripe',
    ats: 'greenhouse',
    token: 'stripe',
    careersUrl: 'https://stripe.com/jobs/search',
    signal: 4,
    tags: ['product', 'fintech', 'remote-global'],
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'comp-postman',
    name: 'Postman',
    normalizedName: 'postman',
    ats: 'greenhouse',
    token: 'postman',
    careersUrl: 'https://www.postman.com/company/careers/',
    signal: 3,
    tags: ['india', 'product', 'remote-india'],
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'comp-grafana',
    name: 'Grafana Labs',
    normalizedName: 'grafana',
    ats: 'greenhouse',
    token: 'grafanalabs',
    careersUrl: 'https://grafana.com/about/careers/',
    signal: 3,
    tags: ['remote-global', 'product', 'oss'],
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'comp-openai',
    name: 'OpenAI',
    normalizedName: 'openai',
    ats: 'ashby',
    token: 'openai',
    careersUrl: 'https://openai.com/careers/',
    signal: 5,
    tags: ['product', 'ai'],
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'comp-palantir',
    name: 'Palantir',
    normalizedName: 'palantir',
    ats: 'lever',
    token: 'palantir',
    careersUrl: 'https://www.palantir.com/careers/',
    signal: 3,
    tags: ['product'],
    enabled: true,
    createdAt: new Date(),
  },
  {
    id: 'comp-vercel',
    name: 'Vercel',
    normalizedName: 'vercel',
    ats: 'ashby',
    token: 'vercel',
    careersUrl: 'https://vercel.com/careers',
    signal: 4,
    tags: ['remote-global', 'product', 'frontend'],
    enabled: true,
    createdAt: new Date(),
  },
];

export const INITIAL_JOBS: Job[] = [
  {
    id: 'job-stripe-1',
    companyId: null,
    source: 'greenhouse',
    sourceId: 'gh-stripe-5829102',
    company: 'Stripe',
    companyNormalized: 'stripe',
    title: 'Senior Full Stack Engineer, Developer Infrastructure',
    titleNormalized: 'senior full stack engineer developer infrastructure',
    url: 'https://boards.greenhouse.io/stripe/jobs/5829102',
    applyUrl: 'https://boards.greenhouse.io/stripe/jobs/5829102#app',
    locationRaw: 'Remote - India',
    locations: ['Remote - India'],
    workMode: 'remote',
    seniority: 'senior',
    descriptionText:
      'We are looking for a Senior Full Stack Engineer to build next-generation developer tooling, unified dashboard components, and high-performance APIs. You will work extensively with React 19, TypeScript, Node.js microservices, Docker, CI/CD pipelines, and GCP Cloud Run. Strong focus on zero-downtime deployments, latency reduction, and robust testing with Jest.',
    salaryMin: 28,
    salaryMax: 38,
    salaryCurrency: 'INR',
    salaryInrLpa: 33,
    postedAt: new Date(Date.now() - 3 * 3600000),
    firstSeenAt: new Date(Date.now() - 3 * 3600000),
    status: 'to_apply',
    tier: 1,
    score: 96,
    breakdown: {
      skillScore: 45,
      seniorityScore: 20,
      salaryScore: 15,
      workModeScore: 10,
      freshnessScore: 6,
    },
    matchedSkills: ['react', 'typescript', 'node.js', 'docker', 'ci/cd', 'gcp', 'jest', 'rest api'],
    gaps: ['aws', 'kubernetes'],
    ghostScore: 0.05,
    ghostReasons: null,
    disqualified: null,
    seenOn: ['greenhouse', 'linkedin'],
    dedupHash: 'stripe::senior-full-stack-engineer-developer-infra::remote-india',
    updatedAt: new Date(),
  },
  {
    id: 'job-postman-1',
    companyId: null,
    source: 'greenhouse',
    sourceId: 'gh-postman-4921021',
    company: 'Postman',
    companyNormalized: 'postman',
    title: 'Senior Full-Stack Engineer — API Platform & Workspaces',
    titleNormalized: 'senior full stack engineer api platform workspaces',
    url: 'https://boards.greenhouse.io/postman/jobs/4921021',
    applyUrl: 'https://boards.greenhouse.io/postman/jobs/4921021#app',
    locationRaw: 'Bengaluru / Remote - India',
    locations: ['Bengaluru, India', 'Remote - India'],
    workMode: 'remote',
    seniority: 'senior',
    descriptionText:
      'Join Postman to scale our real-time collaboration engine. Looking for engineers with hands-on production expertise in React, Redux, Node.js, Fastify/Express, TypeScript, and micro-frontend architectures. Experience with GCP Pub/Sub and automated CI/CD is a huge plus.',
    salaryMin: 30,
    salaryMax: 42,
    salaryCurrency: 'INR',
    salaryInrLpa: 36,
    postedAt: new Date(Date.now() - 5 * 3600000),
    firstSeenAt: new Date(Date.now() - 5 * 3600000),
    status: 'to_apply',
    tier: 1,
    score: 94,
    breakdown: {
      skillScore: 44,
      seniorityScore: 20,
      salaryScore: 15,
      workModeScore: 10,
      freshnessScore: 5,
    },
    matchedSkills: ['react', 'redux', 'node.js', 'typescript', 'fastify', 'gcp', 'ci/cd'],
    gaps: ['kafka'],
    ghostScore: 0.02,
    ghostReasons: null,
    disqualified: null,
    seenOn: ['greenhouse', 'naukri'],
    dedupHash: 'postman::senior-full-stack-engineer-api-platform::remote-india',
    updatedAt: new Date(),
  },
  {
    id: 'job-openai-1',
    companyId: null,
    source: 'ashby',
    sourceId: 'ashby-openai-102938',
    company: 'OpenAI',
    companyNormalized: 'openai',
    title: 'Member of Technical Staff — Full Stack Applications',
    titleNormalized: 'member of technical staff full stack applications',
    url: 'https://jobs.ashbyhq.com/openai/102938',
    applyUrl: 'https://jobs.ashbyhq.com/openai/102938/application',
    locationRaw: 'Remote (Global)',
    locations: ['Remote (Global)'],
    workMode: 'remote',
    seniority: 'senior',
    descriptionText:
      'We are expanding our applications team building intuitive user experiences for ChatGPT Enterprise and developer tools. We require deep mastery of TypeScript, modern React, state synchronization, backend API design in Python or Node.js, and automated end-to-end testing.',
    salaryMin: 160000,
    salaryMax: 220000,
    salaryCurrency: 'USD',
    salaryInrLpa: 157,
    postedAt: new Date(Date.now() - 8 * 3600000),
    firstSeenAt: new Date(Date.now() - 8 * 3600000),
    status: 'to_apply',
    tier: 1,
    score: 92,
    breakdown: {
      skillScore: 42,
      seniorityScore: 20,
      salaryScore: 15,
      workModeScore: 10,
      freshnessScore: 5,
    },
    matchedSkills: ['react', 'typescript', 'node.js', 'python', 'rest api', 'docker'],
    gaps: ['kubernetes', 'terraform'],
    ghostScore: 0.0,
    ghostReasons: null,
    disqualified: null,
    seenOn: ['ashby'],
    dedupHash: 'openai::mts-full-stack-applications::remote-global',
    updatedAt: new Date(),
  },
  {
    id: 'job-grafana-1',
    companyId: null,
    source: 'greenhouse',
    sourceId: 'gh-grafana-671201',
    company: 'Grafana Labs',
    companyNormalized: 'grafana',
    title: 'Senior Software Engineer — Cloud Frontends',
    titleNormalized: 'senior software engineer cloud frontends',
    url: 'https://boards.greenhouse.io/grafanalabs/jobs/671201',
    applyUrl: 'https://boards.greenhouse.io/grafanalabs/jobs/671201#app',
    locationRaw: 'Remote - India',
    locations: ['Remote - India'],
    workMode: 'remote',
    seniority: 'senior',
    descriptionText:
      'Grafana Labs is seeking a Senior Frontend / Full-Stack Engineer to lead dashboard visualization features. Production experience in React, TypeScript, WebSocket telemetry, and containerized microservices is required.',
    salaryMin: 26,
    salaryMax: 34,
    salaryCurrency: 'INR',
    salaryInrLpa: 30,
    postedAt: new Date(Date.now() - 14 * 3600000),
    firstSeenAt: new Date(Date.now() - 14 * 3600000),
    status: 'to_apply',
    tier: 1,
    score: 88,
    breakdown: {
      skillScore: 40,
      seniorityScore: 18,
      salaryScore: 15,
      workModeScore: 10,
      freshnessScore: 5,
    },
    matchedSkills: ['react', 'typescript', 'node.js', 'docker', 'jest'],
    gaps: ['go', 'prometheus'],
    ghostScore: 0.01,
    ghostReasons: null,
    disqualified: null,
    seenOn: ['greenhouse', 'linkedin'],
    dedupHash: 'grafana::senior-software-engineer-cloud-frontends::remote-india',
    updatedAt: new Date(),
  },
  {
    id: 'job-palantir-1',
    companyId: null,
    source: 'lever',
    sourceId: 'lever-palantir-89102',
    company: 'Palantir',
    companyNormalized: 'palantir',
    title: 'Senior Full Stack Software Engineer — Foundry Operations',
    titleNormalized: 'senior full stack software engineer foundry operations',
    url: 'https://jobs.lever.co/palantir/89102',
    applyUrl: 'https://jobs.lever.co/palantir/89102/apply',
    locationRaw: 'Remote - India',
    locations: ['Remote - India'],
    workMode: 'remote',
    seniority: 'senior',
    descriptionText:
      'We are looking for seasoned engineers to build scalable data management interfaces. Deep expertise in React, TypeScript, Python backend services, and distributed architectures.',
    salaryMin: 28,
    salaryMax: 36,
    salaryCurrency: 'INR',
    salaryInrLpa: 32,
    postedAt: new Date(Date.now() - 18 * 3600000),
    firstSeenAt: new Date(Date.now() - 18 * 3600000),
    status: 'to_apply',
    tier: 1,
    score: 85,
    breakdown: {
      skillScore: 38,
      seniorityScore: 18,
      salaryScore: 15,
      workModeScore: 10,
      freshnessScore: 4,
    },
    matchedSkills: ['react', 'typescript', 'python', 'rest api', 'docker'],
    gaps: ['java', 'spark'],
    ghostScore: 0.03,
    ghostReasons: null,
    disqualified: null,
    seenOn: ['lever'],
    dedupHash: 'palantir::senior-full-stack-engineer-foundry::remote-india',
    updatedAt: new Date(),
  },
  {
    id: 'job-legacy-1',
    companyId: null,
    source: 'greenhouse',
    sourceId: 'gh-legacy-3312',
    company: 'Legacy Corp',
    companyNormalized: 'legacy corp',
    title: 'Staff Java Backend Architect',
    titleNormalized: 'staff java backend architect',
    url: 'https://boards.greenhouse.io/legacy/3312',
    applyUrl: null,
    locationRaw: 'Onsite - London, UK',
    locations: ['London, UK'],
    workMode: 'onsite',
    seniority: 'staff',
    descriptionText: 'Requires 12+ years of Core Java, Spring Boot, Hibernate, Oracle SQL, and AWS architecture.',
    salaryMin: 85000,
    salaryMax: 110000,
    salaryCurrency: 'GBP',
    salaryInrLpa: 90,
    postedAt: new Date(Date.now() - 48 * 3600000),
    firstSeenAt: new Date(Date.now() - 48 * 3600000),
    status: 'skipped',
    tier: 4,
    score: 18,
    breakdown: {
      skillScore: 0,
      seniorityScore: 10,
      salaryScore: 0,
      workModeScore: 0,
      freshnessScore: 0,
    },
    matchedSkills: [],
    gaps: ['java', 'spring boot', 'aws', 'oracle'],
    ghostScore: 0.8,
    ghostReasons: null,
    disqualified: 'disqualified: wrong stack (0 matched skills, gaps: java, spring boot, aws)',
    seenOn: ['greenhouse'],
    dedupHash: 'legacy::staff-java-backend-architect::london-uk',
    updatedAt: new Date(),
  },
];

export const INITIAL_STATS: StatsResponse = {
  companies: {
    total: 6,
    enabled: 6,
  },
  jobs: {
    total: 6,
    byTier: { '1': 5, '2': 0, '3': 0, '4': 1 },
    byStatus: { to_apply: 5, skipped: 1, applied: 0 },
    bySource: { greenhouse: 4, ashby: 1, lever: 1 },
  },
  lastIngest: {
    at: new Date(Date.now() - 3600000),
    status: 'success',
    fetched: 8,
    inserted: 6,
  },
};

export const INITIAL_EVENTS: Event[] = [
  {
    id: 'evt-1',
    entityType: 'job',
    entityId: 'job-stripe-1',
    action: 'scored',
    actor: 'agent',
    payload: { score: 96, tier: 1, matchedSkills: 8, gaps: 2 },
    screenshotPath: null,
    createdAt: new Date(Date.now() - 4 * 3600000),
  },
  {
    id: 'evt-2',
    entityType: 'ingest',
    entityId: 'run-ingest-today',
    action: 'completed',
    actor: 'agent',
    payload: { fetched: 8, unique: 7, duplicatesCollapsed: 1, tier1: 5 },
    screenshotPath: null,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'evt-3',
    entityType: 'outreach',
    entityId: 'rec-1',
    action: 'dispatched_draft',
    actor: 'user',
    payload: { channel: 'gmail', recipient: 'sarah.jenkins@stripe.com' },
    screenshotPath: null,
    createdAt: new Date(Date.now() - 2 * 3600000),
  },
];
